/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Abed Eid
 */
public class NewJFrame extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet resultSet = null;
    SimpleDateFormat format1 = new SimpleDateFormat("MMM-dd-yyyy");
    java.sql.Date date;

    public void CurrentDate() {

        Thread clock = new Thread() {

            public void run() {

                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int hours = cal.get(Calendar.HOUR);
                    int Minute = cal.get(Calendar.MINUTE);
                    int secound = cal.get(Calendar.SECOND);
                    time.setText("Date : " + day + "/" + (month + 1) + "/" + year + " Time :" + hours + ":" + Minute + ":" + secound);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        };
        clock.start();
    }

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        conn = Connect.connect();
        initComponents();
        CurrentDate();
        Home.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jButton5.setVisible(false);
        jButton8.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HomeP = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PName = new javax.swing.JTextField();
        PName1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        PName3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PName2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Home1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaptionBorder);
        setName(""); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Aسdmin copy.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 220, 60));

        jPanel2.setBackground(new java.awt.Color(57, 70, 78));
        jPanel2.setLayout(new java.awt.CardLayout());

        HomeP.setBackground(new java.awt.Color(57, 75, 78));
        HomeP.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        HomeP.add(jTextField1);
        jTextField1.setBounds(440, 260, 350, 60);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        HomeP.add(jPasswordField1);
        jPasswordField1.setBounds(440, 340, 350, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/دخولbutton.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        HomeP.add(jButton1);
        jButton1.setBounds(570, 440, 150, 40);

        jButton2.setBackground(new java.awt.Color(57, 70, 78));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(57, 75, 78));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/الغاء.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        HomeP.add(jButton2);
        jButton2.setBounds(380, 440, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panel login.png"))); // NOI18N
        HomeP.add(jLabel1);
        jLabel1.setBounds(114, 113, 886, 464);

        jPanel2.add(HomeP, "card2");

        jPanel3.setBackground(new java.awt.Color(57, 70, 78));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("اسم المريض ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(790, 50, 230, 44);

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("2016 / 6 /6");
        jPanel3.add(time);
        time.setBounds(10, 10, 380, 44);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("التشخيص");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(850, 140, 180, 44);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("السن");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(200, 50, 100, 44);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("المـلاحظـات");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(800, 240, 230, 44);

        PName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNameKeyReleased(evt);
            }
        });
        jPanel3.add(PName);
        PName.setBounds(40, 50, 140, 50);

        PName1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PName1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PName1ActionPerformed(evt);
            }
        });
        PName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PName1KeyReleased(evt);
            }
        });
        jPanel3.add(PName1);
        PName1.setBounds(319, 50, 460, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "علاج", "تبيض جير", "حشو عادي", "حشو عصب ", "خلع", "تركيب ثابت ", "تركيب متحرك ", "جراحه ", "تقويم" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.setAlignmentX(1.0F);
        jComboBox1.setAlignmentY(1.0F);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(620, 150, 220, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(310, 210, 470, 160);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/الغاء_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(390, 390, 110, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setRowMargin(5);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 450, 1010, 170);

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel3.add(jDateChooser1);
        jDateChooser1.setBounds(240, 150, 220, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/حفظ_1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(560, 390, 110, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/طباعة تقرير.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(180, 390, 180, 40);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("الاعاده");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(470, 150, 130, 44);

        jPanel2.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(57, 70, 78));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/سشؤقؤا.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 193, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(222, 222, 222))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );

        jPanel2.add(jPanel4, "card4");

        jPanel5.setBackground(new java.awt.Color(57, 70, 78));
        jPanel5.setLayout(null);

        PName3.setEditable(false);
        PName3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PName3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PName3ActionPerformed(evt);
            }
        });
        PName3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PName3KeyReleased(evt);
            }
        });
        jPanel5.add(PName3);
        PName3.setBounds(320, 30, 460, 50);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("اسم المريض ");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(780, 30, 230, 44);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("التشخيص");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(850, 140, 180, 44);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("المـلاحظـات");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(800, 240, 230, 44);

        PName2.setEditable(false);
        PName2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PName2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PName2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PName2KeyReleased(evt);
            }
        });
        jPanel5.add(PName2);
        PName2.setBounds(40, 30, 140, 50);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "علاج", "تبيض جير", "حشو عادي", "حشو عصب ", "خلع", "تركيب ثابت ", "تركيب متحرك ", "جراحه ", "تقويم" }));
        jComboBox3.setSelectedIndex(-1);
        jComboBox3.setAlignmentX(1.0F);
        jComboBox3.setAlignmentY(1.0F);
        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(620, 150, 220, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2);

        jPanel5.add(jScrollPane4);
        jScrollPane4.setBounds(30, 210, 750, 160);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/الغاء_1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(170, 400, 110, 40);

        jDateChooser2.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(jDateChooser2);
        jDateChooser2.setBounds(240, 150, 220, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/حفظ_1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(800, 400, 110, 40);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/طباعة تقرير.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(320, 400, 170, 40);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("الاعاده");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(470, 150, 130, 44);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("السن");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(200, 30, 100, 44);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/طباعة تقريرa copy.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(560, 400, 170, 40);

        jPanel2.add(jPanel5, "card5");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        Home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/دخول.png"))); // NOI18N
        Home1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Home1MouseMoved(evt);
            }
        });
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home1MouseExited(evt);
            }
        });
        jPanel1.add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Admin coسيبpy.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, -1, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/خروج.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(jPanel3);
        jPanel2.repaint();
        jPanel2.revalidate();
        Home.setVisible(true);
        jLabel3.setVisible(true);
        table1();
        reset();

    }//GEN-LAST:event_HomeMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == evt.VK_ENTER) {
            String Name = jTextField1.getText().toLowerCase().trim();
            String password = jPasswordField1.getText().toLowerCase().trim();
            //  if (Name.equals("")) {
            if (Name.equals("zayed clinic") || Name.equals("zayedclinic") && password.equals("01007217140")) {
                Home1.setVisible(false);
                HomeP.setVisible(false);
                jPanel3.setVisible(true);
                Home.setVisible(true);
                jLabel4.setVisible(true);
                jLabel3.setVisible(true);

                table1();

            } else {
                JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل الاسم و الرقم السري الصحيح  ", JOptionPane.ERROR_MESSAGE);
                jTextField1.setText("");
                jPasswordField1.setText("");

            }
        }


    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String Name = jTextField1.getText().toLowerCase().trim();
        String password = jPasswordField1.getText().toLowerCase().trim();
        if (Name.equals("zayed clinic") || Name.equals("zayedclinic") && password.equals("01007217140")) {
            Home1.setVisible(false);
            HomeP.setVisible(false);
            jPanel3.setVisible(true);
            Home.setVisible(true);
            jLabel4.setVisible(true);
            jLabel3.setVisible(true);

            table1();

        } else {
            JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل الاسم و الرقم السري الصحيح  ", JOptionPane.ERROR_MESSAGE);
            jTextField1.setText("");
            jPasswordField1.setText("");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseClicked
        // TODO add your handling code here

        jPanel2.removeAll();
        jPanel2.add(HomeP);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_Home1MouseClicked

    private void PName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PName1ActionPerformed

    private void PNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNameKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_PNameKeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        char c = evt.getKeyChar();
        if (c == evt.VK_ENTER) {
            String Name = jTextField1.getText().toLowerCase().trim();
            String password = jPasswordField1.getText().toLowerCase().trim();
            // if (Name.equals("")) {
            if (Name.equals("zayed clinic") || Name.equals("zayedclinic") && password.equals("01007217140")) {
                Home1.setVisible(false);
                HomeP.setVisible(false);
                jPanel3.setVisible(true);
                Home.setVisible(true);
                jLabel4.setVisible(true);
                jLabel3.setVisible(true);

                table1();

            } else {
                JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل الاسم و الرقم السري الصحيح  ", JOptionPane.ERROR_MESSAGE);
                jTextField1.setText("");
                jPasswordField1.setText("");

            }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:

        String Name = jTextField1.getText().toLowerCase().trim();
        String password = jPasswordField1.getText().toLowerCase().trim();
        if (Name.equals("zayed clinic") || Name.equals("zayedclinic") && password.equals("01007217140")) {
            Home.setVisible(false);
            HomeP.setVisible(false);
            jPanel3.setVisible(true);
            Home.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);

            table1();

        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2KeyPressed

    private void PNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNameKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == evt.VK_BACK_SPACE || c == '.' || c == evt.VK_ENTER)) {
            String S = PName.getText().trim();
            PName.setText(S.substring(0, S.length() - 1));
            evt.consume();
            JOptionPane.showMessageDialog(this, "غير مسموح بكتابه حروف");
        }
    }//GEN-LAST:event_PNameKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
        tablea();

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void PName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PName1KeyReleased
        Thread clock;
        clock = new Thread() {
            @Override
            public void run() {

                while (true) {

                    if (!(PName1.getText().isEmpty())) {

                        String sql = " select id as `الرقم التسلسلي`, Name as `الاسم` , Age  as `العمر `  from clinic  where name like '%" + PName1.getText().trim() + "%'";
                        try {

                            preparedStatement = conn.prepareStatement(sql);
                            resultSet = preparedStatement.executeQuery();

                            if (resultSet.next()) {
                                conn.prepareStatement(sql);
                                preparedStatement = conn.prepareStatement(sql);
                                resultSet = preparedStatement.executeQuery();
                                jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));

                            } else {
                                table2();
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }

                        try {
                            wait();

                        } catch (InterruptedException ex) {
                            // Logger.getLogger(sea.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null, ex.getMessage());
                        }
                    } else {
                        table1();
                        try {
                            wait();

                        } catch (InterruptedException ex) {
                            // Logger.getLogger(sea.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }

        };
        clock.start();
    }//GEN-LAST:event_PName1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        table1();
        reset();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        Thread clock;
        clock = new Thread() {
            @Override
            public void run() {

                while (true) {

                    if (!(jTextField2.getText().isEmpty())) {

                        String sql = " select id as `الرقم التسلسلي`, Name as `الاسم` , Age  as `العمر `  from clinic  where name like '%" + jTextField2.getText().trim() + "%'";
                        try {

                            preparedStatement = conn.prepareStatement(sql);
                            resultSet = preparedStatement.executeQuery();

                            if (resultSet.next()) {
                                conn.prepareStatement(sql);
                                preparedStatement = conn.prepareStatement(sql);
                                resultSet = preparedStatement.executeQuery();
                                jTable2.setModel(DbUtils.resultSetToTableModel(resultSet));

                            } else {
                                tablea();
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }

                        try {
                            wait();

                        } catch (InterruptedException ex) {
                            // Logger.getLogger(sea.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null, ex.getMessage());
                        }
                    } else {
                        tableb();
                        try {
                            wait();

                        } catch (InterruptedException ex) {
                            // Logger.getLogger(sea.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }

        };
        clock.start();
    }//GEN-LAST:event_jTextField2KeyReleased
    String name;
    String age;
    String note;
    String disease;
    String Date1;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (PName1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل الاسم  ", JOptionPane.ERROR_MESSAGE);

        } else if (PName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل  السن", JOptionPane.ERROR_MESSAGE);

        } else if (jComboBox1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل التشخيص ", JOptionPane.ERROR_MESSAGE);

        } else {
            try {
                name = PName1.getText();
                age = PName.getText();
                note = jTextArea1.getText();
                disease = jComboBox1.getSelectedItem().toString();
                Date1 = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();

                conn = Connect.connect();
                String sqls = "select clinic.id ,clinic.`Name`,clinic.Age ,resee.date,resee.diseses,resee.notes from clinic, resee where clinic.id = resee.id and  Name ='" + name + "' and Age ='" + age + "'    ";
                PreparedStatement st = null;
                try {
                    st = conn.prepareStatement(sqls);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "هذا الاسم موجود ...", "الطابعه ", JOptionPane.WARNING_MESSAGE);

                } else {
                    String id = null;
                    try {
                        String sql = "insert into clinic (clinic.`Name`,clinic.`Age`)values ('" + name + "','" + age + "')";
                        preparedStatement = conn.prepareStatement(sql);
                        preparedStatement.execute();

                        String sqll = "select id from clinic where Name ='" + name + "' and Age ='" + age + "' ";
                        PreparedStatement preparedStatementj = conn.prepareStatement(sqll);
                        ResultSet resultSept = preparedStatementj.executeQuery();

                        if (resultSept.next()) {
                            id = resultSept.getString("id");

                        }
                        String sql2 = " INSERT INTO `resee` (`notes`, `date`, `diseses`,id ) VALUES ('" + note + "' , '" + Date1 + "' , '" + disease + "' ,'" + id + "'  )";
                        PreparedStatement preparedStatement2 = conn.prepareStatement(sql2);
                        preparedStatement2.execute();
                        JOptionPane.showMessageDialog(null, "تم حفظ بيانات المريض ");
                        table1();
                        reset();
                        jButton5.setVisible(true);

                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, " خطأ فى تسجيل البيانات" + e.getMessage());
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        JOptionPane.showMessageDialog(null, "من فضلك" + "\n" + " انتظر قليلا.... ", "الطابعه ", JOptionPane.WARNING_MESSAGE);
        try {

            conn = Connect.connect();
            JasperDesign jd = JRXmlLoader.load("D:\\dist\\report3.jrxml");

            String sql = "SELECT\n"
                    + "     clinic.`id` AS clinic_id,\n"
                    + "     clinic.`Name` AS clinic_Name,\n"
                    + "     clinic.`Age` AS clinic_Age,\n"
                    + "     resee.`id` AS resee_id,\n"
                    + "     resee.`date` AS resee_date,\n"
                    + "     resee.`diseses` AS resee_diseses,\n"
                    + "     resee.`notes` AS resee_notes\n"
                    + "FROM\n"
                    + "     `resee` resee INNER JOIN `clinic` clinic ON resee.`id` = clinic.`id` where clinic.id = resee.id and  clinic.`Name` ='" + name + "' and clinic.`Age` ='" + age + "'  and resee.`date` ='" + Date1 + "' and resee.`notes` ='" + note + "' and resee.`diseses` ='" + disease + "'   ";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {

                JRDesignQuery newQuery = new JRDesignQuery();
                newQuery.setText(sql);
                jd.setQuery(newQuery);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                reset();
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void PName2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PName2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PName2KeyPressed

    private void PName2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PName2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PName2KeyReleased

    private void PName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PName3ActionPerformed

    private void PName3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PName3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PName3KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.add(jPanel3);
        jPanel2.repaint();
        jPanel2.revalidate();


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        if (jComboBox3.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Erorr", "من فضلك ادخل التشخيص ", JOptionPane.ERROR_MESSAGE);

        } else {

            name = PName3.getText();
            age = PName2.getText();
            note = jTextArea2.getText();
            disease = jComboBox3.getSelectedItem().toString();
            Date1 = ((JTextField) jDateChooser2.getDateEditor().getUiComponent()).getText();

            conn = Connect.connect();

            String id = null;
            try {

                String sqll = "select id from clinic where Name ='" + name + "' and Age ='" + age + "' ";
                PreparedStatement preparedStatementj = conn.prepareStatement(sqll);
                ResultSet resultSept = preparedStatementj.executeQuery();

                if (resultSept.next()) {
                    id = resultSept.getString("id");

                }
                String sql2 = " INSERT INTO `resee` (`notes`, `date`, `diseses`,id ) VALUES ('" + note + "' , '" + Date1 + "' , '" + disease + "' ,'" + id + "'  )";
                PreparedStatement preparedStatement2 = conn.prepareStatement(sql2);
                preparedStatement2.execute();
                JOptionPane.showMessageDialog(null, "تم حفظ بيانات المريض ");
                table1();
                reset2();
                jButton8.setVisible(true);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, " خطأ فى تسجيل البيانات" + e.getMessage());
            }

            reset2();

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "من فضلك" + "\n" + " انتظر قليلا.... ", "الطابعه ", JOptionPane.WARNING_MESSAGE);
        try {

            conn = Connect.connect();
            JasperDesign jd = JRXmlLoader.load("D:\\dist\\report3.jrxml");

            String sql = "SELECT\n"
                    + "     clinic.`id` AS clinic_id,\n"
                    + "     clinic.`Name` AS clinic_Name,\n"
                    + "     clinic.`Age` AS clinic_Age,\n"
                    + "     resee.`id` AS resee_id,\n"
                    + "     resee.`date` AS resee_date,\n"
                    + "     resee.`diseses` AS resee_diseses,\n"
                    + "     resee.`notes` AS resee_notes\n"
                    + "FROM\n"
                    + "     `resee` resee INNER JOIN `clinic` clinic ON resee.`id` = clinic.`id` where clinic.id = resee.id and  clinic.`Name` ='" + Name + "' and clinic.`Age` ='" + Age + "'  and resee.`date` ='" + Date1 + "' and resee.`notes` ='" + note + "' and resee.`diseses` ='" + disease + "'   ";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {

                JRDesignQuery newQuery = new JRDesignQuery();
                newQuery.setText(sql);
                jd.setQuery(newQuery);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                reset();
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

        jButton8.setVisible(false);


        /*/////*/

    }//GEN-LAST:event_jButton8ActionPerformed
    String Name;
    String Age;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        try {
            int r = jTable2.getSelectedRow();
            String data = jTable2.getModel().getValueAt(r, 0).toString();
            String sql = " select * from clinic ,resee where  clinic.id ='" + data + "'";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {

                Name = resultSet.getString("clinic.Name");
                PName3.setText(Name);

                Age = Integer.toString(resultSet.getInt("clinic.Age"));
                PName2.setText(Age);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        jPanel2.removeAll();
        jPanel2.add(jPanel5);
        jPanel2.repaint();
        jPanel2.revalidate();

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "من فضلك" + "\n" + " انتظر قليلا.... ", "الطابعه ", JOptionPane.WARNING_MESSAGE);
        try {

            conn = Connect.connect();
            JasperDesign jd = JRXmlLoader.load("D:\\dist\\report4.jrxml");

            String sql = "SELECT\n"
                    + "     clinic.`id` AS clinic_id,\n"
                    + "     clinic.`Name` AS clinic_Name,\n"
                    + "     clinic.`Age` AS clinic_Age,\n"
                    + "     resee.`id` AS resee_id,\n"
                    + "     resee.`date` AS resee_date,\n"
                    + "     resee.`diseses` AS resee_diseses,\n"
                    + "     resee.`notes` AS resee_notes\n"
                    + "FROM\n"
                    + "     `resee` resee INNER JOIN `clinic` clinic ON resee.`id` = clinic.`id` where clinic.id = resee.id and  clinic.`Name` ='" + Name + "' and clinic.`Age` ='" + Age + "' ";

            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {

                JRDesignQuery newQuery = new JRDesignQuery();
                newQuery.setText(sql);
                jd.setQuery(newQuery);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);
                reset();
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

        jButton8.setVisible(false);


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Home1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Home1MouseMoved

    private void Home1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Home1MouseExited

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1MouseMoved

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          try {
            int r = jTable1.getSelectedRow();
            String data = jTable1.getModel().getValueAt(r, 0).toString();
            String sql = " select * from clinic ,resee where  clinic.id ='" + data + "'";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {

                Name = resultSet.getString("clinic.Name");
                PName3.setText(Name);

                Age = Integer.toString(resultSet.getInt("clinic.Age"));
                PName2.setText(Age);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        jPanel2.removeAll();
        jPanel2.add(jPanel5);
        jPanel2.repaint();
        jPanel2.revalidate();

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Home1;
    private javax.swing.JPanel HomeP;
    private javax.swing.JTextField PName;
    private javax.swing.JTextField PName1;
    private javax.swing.JTextField PName2;
    private javax.swing.JTextField PName3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    private void table1() {
        try {
            String sql = " select clinic.id as `الرقم التسلسلي`,  clinic.Name as `الاسم` , clinic.Age  as `العمر ` FROM  clinic";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            PreparedStatement preparedStatement1 = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement1.executeQuery();
            if (resultSet.next()) {
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e.getMessage());

        }
    }

    private void table2() {
        try {
            String sql = " select clinic.id as `الرقم التسلسلي`,  clinic.Name as `الاسم` , clinic.Age  as `العمر `   FROM  clinic where clinic.id is null";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            PreparedStatement preparedStatement1 = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement1.executeQuery();
            if (!resultSet.next()) {
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e.getMessage());

        }
    }

    private void tablea() {
        try {
            String sql = " select clinic.id as `الرقم التسلسلي`,  clinic.Name as `الاسم` , clinic.Age  as `العمر ` FROM  clinic";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            PreparedStatement preparedStatement1 = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement1.executeQuery();
            if (resultSet.next()) {
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e.getMessage());

        }
    }

    private void tableb() {
        try {
            String sql = " select clinic.id as `الرقم التسلسلي`,  clinic.Name as `الاسم` , clinic.Age  as `العمر `   FROM  clinic where clinic.id is null";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            PreparedStatement preparedStatement1 = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement1.executeQuery();
            if (!resultSet.next()) {
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e.getMessage());

        }
    }

    private void table3() {
        try {
            String sql = " select clinic.id as `الرقم التسلسلي`,  clinic.Name as `الاسم` , clinic.Age  as `العمر ` ,resee.date as`تاريخ الاعاده` ,resee.diseses as`التشخيص`, resee.notes as `الملاحظات`  FROM resee , clinic";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            PreparedStatement preparedStatement1 = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement1.executeQuery();
            if (resultSet.next()) {
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e.getMessage());

        }
    }

    private void table4() {
        try {
            String sql = " select clinic.id as `الرقم التسلسلي`,  clinic.Name as `الاسم` , clinic.Age  as `العمر ` ,resee.date as`تاريخ الاعاده` ,resee.diseses as`التشخيص`, resee.notes as `الملاحظات`  FROM resee , clinic where clinic.id is null";
            preparedStatement = conn.prepareStatement(sql);
            resultSet = preparedStatement.executeQuery();
            PreparedStatement preparedStatement1 = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement1.executeQuery();
            if (!resultSet.next()) {
                jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e.getMessage());
        }
    }

    private void reset() {
        PName.setText("");
        PName1.setText("");
        jDateChooser1.setDate(null);
        jComboBox1.setSelectedIndex(-1);
        jTextArea1.setText("");
        jButton5.setVisible(false);

    }

    private void reset2() {
        PName2.setText("");
        PName3.setText("");
        jDateChooser2.setDate(null);
        jComboBox3.setSelectedIndex(-1);
        jTextArea2.setText("");
        jButton9.setVisible(true);
    }

}
